#!/bin/bash
set -eu

# Change this to the location where you installed the jar file.
JAR=/usr/bin/lsd.jar
HEAP_SIZE=-Xmx4G

CLASSPATH=$JAR:./
java $HEAP_SIZE -cp $CLASSPATH org.anc.lapps.dsl.LappsDsl "$@"


