categories: 
  - NLP
description: GATE Processing Resources as LAPPS services.
long_description: |
  Processing resources from GATE (General Architecture for Text Engineering).
name: lapps_gate
owner: ksuderman
remote_repository_url: https://github.com/oanc/org.anc.lapps.gate
homepage_url: http://www.lappsgrid.org


