categories: [NLP]
description: GATE NLP services
long_description: |
  GATE (General Architecture for Text Engineering)
name: lapps_gate
owner: ksuderman
long_description: GATE processing resources provided by the Language Application Grid.
remote_repository_url: https://github.com/org.anc.lapps.gate
homepage_url: http://www.lappsgrid.org


